name: Guilds
version: @version@
main: me.glaremasters.guilds.Main
softdepend: [MVdWPlaceholderAPI, PlaceholderAPI, Vault]
authors: [blockslayer22]
description: Lightweight, flexible, popular plugin for any Minecraft server. Forget Factions! Guilds are here!
website: https://glaremasters.me/guilds/

commands:
  guild:
    aliases: "guilds"
    description: See the Guild commands
  guild accept:
    description: /guild accept <guild name>
  guild admin:
    description: /guild admin <remove | info> <guild name>, or <addplayer | removeplayer> <guild name> <player name>
  guild ally:
    description: /guild ally <add | remove> <guild>, or chat <guild>
  guild boot:
    description: /guild boot <add | remove> <guild>, or chat <guild>
  guild bugreport:
    description: Submit a bug report!
  guild cancel:
    description: Cancel an action
  guild chat:
    description: /guild chat <message>
  guild confirm:
    description: Confirm an action
  guild create:
    description: /guild create <guild name>
  guild delete:
    description: Delete your current guild
  guild demote:
    description: /guild demote <player> [new role]
  guild home:
    description: Teleport to your guild home
  guild info:
    description: View your guild's info
  guild inspect:
    description: /guild inspect <guild name>
  guild invite:
    description: /guild invite <player>
  guild leave:
    description: Leave your current guild
  guild list:
    description: List all guilds on the server
  guild prefix:
    description: /guild prefix <new prefix>
  guild promote:
    description: /guild promote <player> [new role]
  guild reload:
    description: Reload Guilds' configuration file
  guild sethome:
    description: Set your guild's home!
  guild update:
    description: Update to the most recent version of Guilds
  guild version:
    description: Check version
  guild status:
    description: Toggle your guild Public / Private
  guild vault:
    description: Open your Guild Vault!
  guild transfer:
    description: Transfer your guild to a new member!


permissions:
  guilds.group.admin:
    description: All commands for the Guilds plugin
    children:
      guilds.command.accept: true
      guilds.command.admin: true
      guilds.command.boot: true
      guilds.command.cancel: true
      guilds.command.chat: true
      guilds.command.confirm: true
      guilds.command.create: true
      guilds.command.delete: true
      guilds.command.demote: true
      guilds.command.help: true
      guilds.command.info: true
      guilds.command.invite: true
      guilds.command.leave: true
      guilds.command.prefix: true
      guilds.command.promote: true
      guilds.command.reload: true
      guilds.command.role: true
      guilds.command.update: true
    default: op
  guilds.group.member:
    description: All commands for the Guilds plugin
    children:
      guilds.command.accept: true
      guilds.command.boot: true
      guilds.command.cancel: true
      guilds.command.chat: true
      guilds.command.confirm: true
      guilds.command.create: true
      guilds.command.delete: true
      guilds.command.demote: true
      guilds.command.help: true
      guilds.command.info: true
      guilds.command.invite: true
      guilds.command.leave: true
      guilds.command.prefix: true
      guilds.command.promote: true
      guilds.command.role: true
      guilds.command.version: true
      guilds.command.list: true
      guilds.command.bugreport: true
      guilds.command.home: true
      guilds.command.sethome: true
      guilds.command.inspect: true
      guilds.command.status: true
      guilds.command.vault: true
      guilds.command.ally: true
    default: true